version: "3.8"

name: ecommerce-mysql-stack

services:

  mysql-order:
    image: mysql:8.0
    container_name: mysql-order
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orderdb
      MYSQL_USER: order
      MYSQL_PASSWORD: order123
    ports:
      - "3307:3306"   # localhost port
    volumes:
      - order_data:/var/lib/mysql

  mysql-payment:
    image: mysql:8.0
    container_name: mysql-payment
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paymentdb
      MYSQL_USER: payment
      MYSQL_PASSWORD: payment123
    ports:
      - "3308:3306"
    volumes:
      - payment_data:/var/lib/mysql

  mysql-inventory:
    image: mysql:8.0
    container_name: mysql-inventory
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventorydb
      MYSQL_USER: inventory
      MYSQL_PASSWORD: inventory123
    ports:
      - "3309:3306"
    volumes:
      - inventory_data:/var/lib/mysql

volumes:
  order_data:
  payment_data:
  inventory_data:
