server.port=9090
spring.application.name=api-gateway

euraka.client.service-url.defaultZone=http://localhost:8761/eureka/


#Actuator
management.health.circuitbreakers.enabled=true
management.endpoint.health.show-details=always
management.health.resilience4j.enabled=true
management.endpoints.web.exposure.include=health,info,metrics

#Security
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/ecommerce

#Circuit Breaker
# Order Service Circuit Breaker
resilience4j.circuitbreaker.instances.orderServiceCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.orderServiceCircuitBreaker.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.orderServiceCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.orderServiceCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.orderServiceCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.orderServiceCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.orderServiceCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.orderServiceCircuitBreaker.slowCallRateThreshold=100
resilience4j.circuitbreaker.instances.orderServiceCircuitBreaker.slowCallDurationThreshold=2s

# Retry
resilience4j.retry.instances.orderServiceRetry.maxAttempts=3
resilience4j.retry.instances.orderServiceRetry.waitDuration=500ms




# Timeout (TimeLimiter)
resilience4j.timelimiter.instances.orderServiceTimeLimiter.timeoutDuration=4s

# Payment Service Circuit Breaker
resilience4j.circuitbreaker.instances.paymentServiceCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.paymentServiceCircuitBreaker.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.paymentServiceCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.paymentServiceCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.paymentServiceCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.paymentServiceCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentServiceCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.paymentServiceCircuitBreaker.slowCallRateThreshold=100
resilience4j.circuitbreaker.instances.paymentServiceCircuitBreaker.slowCallDurationThreshold=2s

# Retry
resilience4j.retry.instances.paymentServiceRetry.maxAttempts=3
resilience4j.retry.instances.paymentServiceRetry.waitDuration=500ms

# Timeout (TimeLimiter)
resilience4j.timelimiter.instances.paymentServiceCircuitBreaker.timeoutDuration=4s

# Inventory Service Circuit Breaker
resilience4j.circuitbreaker.instances.inventoryServiceCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.inventoryServiceCircuitBreaker.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.inventoryServiceCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.inventoryServiceCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.inventoryServiceCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.inventoryServiceCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventoryServiceCircuitBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.inventoryServiceCircuitBreaker.slowCallRateThreshold=100
resilience4j.circuitbreaker.instances.inventoryServiceCircuitBreaker.slowCallDurationThreshold=2s

# Retry
resilience4j.retry.instances.inventoryServiceRetry.maxAttempts=3
resilience4j.retry.instances.inventoryServiceRetry.waitDuration=500ms

# Timeout (TimeLimiter)
resilience4j.timelimiter.instances.inventoryServiceTimeLimiter.timeoutDuration=4s

# Sampling probability (100% of requests traced)
management.tracing.sampling.probability=1.0

# Zipkin endpoint
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
logging.pattern.level=%5p [%X{spring.application.name:-},%X{traceId:-},%X{spanId:-}] %m%n