server.port=8761

spring.application.name=discovery-server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false


management.endpoints.web.exposure.include=health,info
management.endpoints.health.show-details=always


# Sampling probability (100% of requests traced)
management.tracing.sampling.probability=1.0

# Zipkin endpoint
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
logging.pattern.level=%5p [%X{spring.application.name:-},%X{traceId:-},%X{spanId:-}] %m%n